  - platform: aarlo
    monitored_conditions:
    - total_cameras
    - last_capture
    - recent_activity
    - captured_today
    - battery_level
    - signal_strength
    - temperature
    - humidity
    - air_quality
  - platform: foobot
    token: !secret foobot_token
    username: !secret foobot_username
  - platform: badnest
