  - platform: rpi_power
    text_state: True
  - platform: systemmonitor
    resources:
      - type: last_boot
      - type: disk_use_percent
        arg: /media/usb0/
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: processor_use
      - type: load_15m
      - type: swap_use_percent
  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(0) }}'
  - platform: uptime
#
# Installed hass.io version
  - platform: version
    name: Installed Version
    source: local
#
# Latest Available HA Version
  - platform: version
    name: Latest Available Version
    beta: false
    image: raspberrypi3
    source: hassio
