- id: turn_fish_tank_light_on_in_the_morning
  alias: Turn Fish Tank Light On In The Morning
  trigger:
  - platform: time
    at: '07:15:00'
  action:
  - service: light.turn_on
    entity_id: light.fish_tank_light

- id: turn_fish_tank_light_off_after_8_hours
  alias: Turn Fish Tank Light Off After 8 Hoyrse
  trigger:
  - platform: time
    at: '15:15:00'
  action:
  - service: light.turn_off
    entity_id: light.fish_tank_light
