- id: toggle_attention_needed_in_the_kitchen_nfc
  alias: Toggle Attention Needed In The Kitchen Via NFC
  trigger:
    platform: tag
    tag_id: !secret kitchen_attention_nfc_tag_id
  action:
  - service: input_boolean.toggle
    data:
      entity_id: input_boolean.attention_needed_in_the_kitchen
